# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: Build

on:
  push:
    branches: [ master, cli ]
  pull_request:
    branches: [ master, cli ]
  #schedule:
  #  - cron: '0 0 * * *'


jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}

    steps:
      - uses: actions/checkout@v2
      - name: Set up R ${{ matrix.config.os }} (${{ matrix.config.r }})
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "curl"))
          remotes::install_deps(dependencies = TRUE)
          mv bin/GISAIDR /usr/local/bin
        shell: Rscript {0}
      - name: Check
        env:
          GISAIDR_PASSWORD: ${{ secrets.GISAIDR_PASSWORD }}
          GISAIDR_USERNAME: ${{ secrets.GISAIDR_USERNAME }}
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
      - name: CLI Check
        run: |
          GISAIDR --version
          GISAIDR --help
